services:
  torotrader.webapi:
    image: ${DOCKER_REGISTRY-}torotraderwebapi
    build:
      context: .
      dockerfile: ToroTrader.WebApi/ToroTrader.WebApi/Dockerfile
  db:
    image: postgres:alpine

volumes:
    db_data: